export const RETRIEVE_BUDGET_CATS_REQUESTED = 'RETRIEVE_BUDGET_CATS_REQUESTED';
export const RETRIEVE_BUDGET_CATS_SUCCESS = 'RETRIEVE_BUDGET_CATS_SUCCESS';
export const RETRIEVE_BUDGET_CATS_FAIL = 'RETRIEVE_BUDGET_CATS_FAIL';
export const CREATE_BUDGET_CAT = 'CREATE_BUDGET_CAT';
