export const RETRIEVE_TRANSACTIONS_REQUESTED = "RETRIEVE_TRANSACTIONS_REQUESTED";
export const RETRIEVE_TRANSACTIONS_SUCCESS = "RETRIEVE_TRANSACTIONS_SUCCESS";
export const RETRIEVE_TRANSACTIONS_FAIL = "RETRIEVE_TRANSACTIONS_FAIL";
