export const RETRIEVE_TRANSACTIONS_REQUESTED = "RETRIEVE_TRANSACTIONS_REQUESTED";
export const RETRIEVE_TRANSACTIONS_SUCCESS = "RETRIEVE_TRANSACTIONS_SUCCESS";
export const RETRIEVE_TRANSACTIONS_FAIL = "RETRIEVE_TRANSACTIONS_FAIL";

export const CREATE_TRANSACTION_REQUESTED = "CREATE_TRANSACTION_REQUESTED";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";
